// Code generated by capwrap-gen. DO NOT EDIT.

package calc

import (
	"context"

	capnp "capnproto.org/go/capnp/v3"
	capwrap "github.com/Huy-8bit/capwrap/runtime"
)

// CalculatorServer is the service interface application code implements.
type CalculatorServer interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	Add(context.Context, *AddRequest) (*AddResponse, error)
}

// CalculatorClient calls a remote Calculator service.
type CalculatorClient interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Close() error
}

type SayHelloRequest struct {
	Name string
}

type SayHelloResponse struct {
	Message string
}

type AddRequest struct {
	A int64
	B int64
}

type AddResponse struct {
	Sum int64
}

// RegisterCalculatorServer installs impl as the server's bootstrap capability.
func RegisterCalculatorServer(s *capwrap.Server, impl CalculatorServer) {
	s.SetBootstrap(capnp.Client(Calculator_ServerToClient(calculatorServerAdapter{impl})))
}

type calculatorServerAdapter struct {
	impl CalculatorServer
}

func (s calculatorServerAdapter) SayHello(ctx context.Context, call Calculator_sayHello) error {
	args := call.Args()
	argName, err := args.Name()
	if err != nil {
		return err
	}
	resp, err := s.impl.SayHello(ctx, &SayHelloRequest{
		Name: argName,
	})
	if err != nil {
		return err
	}
	results, err := call.AllocResults()
	if err != nil {
		return err
	}
	if err := results.SetMessageText(resp.Message); err != nil {
		return err
	}
	return nil
}

func (s calculatorServerAdapter) Add(ctx context.Context, call Calculator_add) error {
	args := call.Args()
	argA := args.A()
	argB := args.B()
	resp, err := s.impl.Add(ctx, &AddRequest{
		A: argA,
		B: argB,
	})
	if err != nil {
		return err
	}
	results, err := call.AllocResults()
	if err != nil {
		return err
	}
	results.SetSum(resp.Sum)
	return nil
}

func (s calculatorServerAdapter) Summarize(ctx context.Context, call Calculator_summarize) error {
	// field "items" has unsupported type "List(ComplexItem)"
	return capwrap.Errorf("method Summarize is not supported by the capwrap wrapper")
}

// DialCalculator connects to a Calculator service at addr.
func DialCalculator(ctx context.Context, addr string, opts ...capwrap.DialOption) (CalculatorClient, error) {
	cc, err := capwrap.Dial(ctx, addr, opts...)
	if err != nil {
		return nil, err
	}
	return &calculatorClient{cc: cc, raw: Calculator(cc.Bootstrap(ctx))}, nil
}

type calculatorClient struct {
	cc  *capwrap.ClientConn
	raw Calculator
}

func (c *calculatorClient) Close() error {
	c.raw.Release()
	return c.cc.Close()
}

func (c *calculatorClient) SayHello(ctx context.Context, req *SayHelloRequest) (*SayHelloResponse, error) {
	future, release := c.raw.SayHello(ctx, func(p Calculator_sayHello_Params) error {
		if err := p.SetName(req.Name); err != nil {
			return err
		}
		return nil
	})
	defer release()

	res, err := future.Struct()
	if err != nil {
		return nil, capwrap.WrapError(err)
	}
	retMessage, err := res.MessageText()
	if err != nil {
		return nil, capwrap.WrapError(err)
	}
	return &SayHelloResponse{
		Message: retMessage,
	}, nil
}

func (c *calculatorClient) Add(ctx context.Context, req *AddRequest) (*AddResponse, error) {
	future, release := c.raw.Add(ctx, func(p Calculator_add_Params) error {
		p.SetA(req.A)
		p.SetB(req.B)
		return nil
	})
	defer release()

	res, err := future.Struct()
	if err != nil {
		return nil, capwrap.WrapError(err)
	}
	retSum := res.Sum()
	return &AddResponse{
		Sum: retSum,
	}, nil
}
