// Code generated by capnpc-go. DO NOT EDIT.

package calc

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	math "math"
)

type Calculator capnp.Client

// Calculator_TypeID is the unique identifier for the type Calculator.
const Calculator_TypeID = 0x8859bd865a77111d

func (c Calculator) SayHello(ctx context.Context, params func(Calculator_sayHello_Params) error) (Calculator_sayHello_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8859bd865a77111d,
			MethodID:      0,
			InterfaceName: "calculator.capnp:Calculator",
			MethodName:    "sayHello",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Calculator_sayHello_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Calculator_sayHello_Results_Future{Future: ans.Future()}, release

}

func (c Calculator) Add(ctx context.Context, params func(Calculator_add_Params) error) (Calculator_add_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8859bd865a77111d,
			MethodID:      1,
			InterfaceName: "calculator.capnp:Calculator",
			MethodName:    "add",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Calculator_add_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Calculator_add_Results_Future{Future: ans.Future()}, release

}

func (c Calculator) Summarize(ctx context.Context, params func(Calculator_summarize_Params) error) (Calculator_summarize_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8859bd865a77111d,
			MethodID:      2,
			InterfaceName: "calculator.capnp:Calculator",
			MethodName:    "summarize",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Calculator_summarize_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Calculator_summarize_Results_Future{Future: ans.Future()}, release

}

func (c Calculator) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Calculator) String() string {
	return "Calculator(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Calculator) AddRef() Calculator {
	return Calculator(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Calculator) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Calculator) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Calculator) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Calculator) DecodeFromPtr(p capnp.Ptr) Calculator {
	return Calculator(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Calculator) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Calculator) IsSame(other Calculator) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Calculator) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Calculator) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Calculator_Server is a Calculator with a local implementation.
type Calculator_Server interface {
	SayHello(context.Context, Calculator_sayHello) error

	Add(context.Context, Calculator_add) error

	Summarize(context.Context, Calculator_summarize) error
}

// Calculator_NewServer creates a new Server from an implementation of Calculator_Server.
func Calculator_NewServer(s Calculator_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Calculator_Methods(nil, s), s, c)
}

// Calculator_ServerToClient creates a new Client from an implementation of Calculator_Server.
// The caller is responsible for calling Release on the returned Client.
func Calculator_ServerToClient(s Calculator_Server) Calculator {
	return Calculator(capnp.NewClient(Calculator_NewServer(s)))
}

// Calculator_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Calculator_Methods(methods []server.Method, s Calculator_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8859bd865a77111d,
			MethodID:      0,
			InterfaceName: "calculator.capnp:Calculator",
			MethodName:    "sayHello",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.SayHello(ctx, Calculator_sayHello{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8859bd865a77111d,
			MethodID:      1,
			InterfaceName: "calculator.capnp:Calculator",
			MethodName:    "add",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Add(ctx, Calculator_add{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8859bd865a77111d,
			MethodID:      2,
			InterfaceName: "calculator.capnp:Calculator",
			MethodName:    "summarize",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Summarize(ctx, Calculator_summarize{call})
		},
	})

	return methods
}

// Calculator_sayHello holds the state for a server call to Calculator.sayHello.
// See server.Call for documentation.
type Calculator_sayHello struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Calculator_sayHello) Args() Calculator_sayHello_Params {
	return Calculator_sayHello_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Calculator_sayHello) AllocResults() (Calculator_sayHello_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Calculator_sayHello_Results(r), err
}

// Calculator_add holds the state for a server call to Calculator.add.
// See server.Call for documentation.
type Calculator_add struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Calculator_add) Args() Calculator_add_Params {
	return Calculator_add_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Calculator_add) AllocResults() (Calculator_add_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Calculator_add_Results(r), err
}

// Calculator_summarize holds the state for a server call to Calculator.summarize.
// See server.Call for documentation.
type Calculator_summarize struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Calculator_summarize) Args() Calculator_summarize_Params {
	return Calculator_summarize_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Calculator_summarize) AllocResults() (Calculator_summarize_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return Calculator_summarize_Results(r), err
}

// Calculator_List is a list of Calculator.
type Calculator_List = capnp.CapList[Calculator]

// NewCalculator_List creates a new list of Calculator.
func NewCalculator_List(s *capnp.Segment, sz int32) (Calculator_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Calculator](l), err
}

type Calculator_sayHello_Params capnp.Struct

// Calculator_sayHello_Params_TypeID is the unique identifier for the type Calculator_sayHello_Params.
const Calculator_sayHello_Params_TypeID = 0xbe6632926ad545b7

func NewCalculator_sayHello_Params(s *capnp.Segment) (Calculator_sayHello_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Calculator_sayHello_Params(st), err
}

func NewRootCalculator_sayHello_Params(s *capnp.Segment) (Calculator_sayHello_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Calculator_sayHello_Params(st), err
}

func ReadRootCalculator_sayHello_Params(msg *capnp.Message) (Calculator_sayHello_Params, error) {
	root, err := msg.Root()
	return Calculator_sayHello_Params(root.Struct()), err
}

func (s Calculator_sayHello_Params) String() string {
	str, _ := text.Marshal(0xbe6632926ad545b7, capnp.Struct(s))
	return str
}

func (s Calculator_sayHello_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Calculator_sayHello_Params) DecodeFromPtr(p capnp.Ptr) Calculator_sayHello_Params {
	return Calculator_sayHello_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Calculator_sayHello_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Calculator_sayHello_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Calculator_sayHello_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Calculator_sayHello_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Calculator_sayHello_Params) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Calculator_sayHello_Params) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Calculator_sayHello_Params) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Calculator_sayHello_Params) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Calculator_sayHello_Params_List is a list of Calculator_sayHello_Params.
type Calculator_sayHello_Params_List = capnp.StructList[Calculator_sayHello_Params]

// NewCalculator_sayHello_Params creates a new list of Calculator_sayHello_Params.
func NewCalculator_sayHello_Params_List(s *capnp.Segment, sz int32) (Calculator_sayHello_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Calculator_sayHello_Params](l), err
}

// Calculator_sayHello_Params_Future is a wrapper for a Calculator_sayHello_Params promised by a client call.
type Calculator_sayHello_Params_Future struct{ *capnp.Future }

func (f Calculator_sayHello_Params_Future) Struct() (Calculator_sayHello_Params, error) {
	p, err := f.Future.Ptr()
	return Calculator_sayHello_Params(p.Struct()), err
}

type Calculator_sayHello_Results capnp.Struct

// Calculator_sayHello_Results_TypeID is the unique identifier for the type Calculator_sayHello_Results.
const Calculator_sayHello_Results_TypeID = 0x91cea401ebb7ded5

func NewCalculator_sayHello_Results(s *capnp.Segment) (Calculator_sayHello_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Calculator_sayHello_Results(st), err
}

func NewRootCalculator_sayHello_Results(s *capnp.Segment) (Calculator_sayHello_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Calculator_sayHello_Results(st), err
}

func ReadRootCalculator_sayHello_Results(msg *capnp.Message) (Calculator_sayHello_Results, error) {
	root, err := msg.Root()
	return Calculator_sayHello_Results(root.Struct()), err
}

func (s Calculator_sayHello_Results) String() string {
	str, _ := text.Marshal(0x91cea401ebb7ded5, capnp.Struct(s))
	return str
}

func (s Calculator_sayHello_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Calculator_sayHello_Results) DecodeFromPtr(p capnp.Ptr) Calculator_sayHello_Results {
	return Calculator_sayHello_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Calculator_sayHello_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Calculator_sayHello_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Calculator_sayHello_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Calculator_sayHello_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Calculator_sayHello_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Calculator_sayHello_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Calculator_sayHello_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Calculator_sayHello_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Calculator_sayHello_Results_List is a list of Calculator_sayHello_Results.
type Calculator_sayHello_Results_List = capnp.StructList[Calculator_sayHello_Results]

// NewCalculator_sayHello_Results creates a new list of Calculator_sayHello_Results.
func NewCalculator_sayHello_Results_List(s *capnp.Segment, sz int32) (Calculator_sayHello_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Calculator_sayHello_Results](l), err
}

// Calculator_sayHello_Results_Future is a wrapper for a Calculator_sayHello_Results promised by a client call.
type Calculator_sayHello_Results_Future struct{ *capnp.Future }

func (f Calculator_sayHello_Results_Future) Struct() (Calculator_sayHello_Results, error) {
	p, err := f.Future.Ptr()
	return Calculator_sayHello_Results(p.Struct()), err
}

type Calculator_add_Params capnp.Struct

// Calculator_add_Params_TypeID is the unique identifier for the type Calculator_add_Params.
const Calculator_add_Params_TypeID = 0xb71b093273c5896a

func NewCalculator_add_Params(s *capnp.Segment) (Calculator_add_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Calculator_add_Params(st), err
}

func NewRootCalculator_add_Params(s *capnp.Segment) (Calculator_add_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Calculator_add_Params(st), err
}

func ReadRootCalculator_add_Params(msg *capnp.Message) (Calculator_add_Params, error) {
	root, err := msg.Root()
	return Calculator_add_Params(root.Struct()), err
}

func (s Calculator_add_Params) String() string {
	str, _ := text.Marshal(0xb71b093273c5896a, capnp.Struct(s))
	return str
}

func (s Calculator_add_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Calculator_add_Params) DecodeFromPtr(p capnp.Ptr) Calculator_add_Params {
	return Calculator_add_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Calculator_add_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Calculator_add_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Calculator_add_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Calculator_add_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Calculator_add_Params) A() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s Calculator_add_Params) SetA(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s Calculator_add_Params) B() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s Calculator_add_Params) SetB(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

// Calculator_add_Params_List is a list of Calculator_add_Params.
type Calculator_add_Params_List = capnp.StructList[Calculator_add_Params]

// NewCalculator_add_Params creates a new list of Calculator_add_Params.
func NewCalculator_add_Params_List(s *capnp.Segment, sz int32) (Calculator_add_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[Calculator_add_Params](l), err
}

// Calculator_add_Params_Future is a wrapper for a Calculator_add_Params promised by a client call.
type Calculator_add_Params_Future struct{ *capnp.Future }

func (f Calculator_add_Params_Future) Struct() (Calculator_add_Params, error) {
	p, err := f.Future.Ptr()
	return Calculator_add_Params(p.Struct()), err
}

type Calculator_add_Results capnp.Struct

// Calculator_add_Results_TypeID is the unique identifier for the type Calculator_add_Results.
const Calculator_add_Results_TypeID = 0xe3188e9225bd9f50

func NewCalculator_add_Results(s *capnp.Segment) (Calculator_add_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Calculator_add_Results(st), err
}

func NewRootCalculator_add_Results(s *capnp.Segment) (Calculator_add_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Calculator_add_Results(st), err
}

func ReadRootCalculator_add_Results(msg *capnp.Message) (Calculator_add_Results, error) {
	root, err := msg.Root()
	return Calculator_add_Results(root.Struct()), err
}

func (s Calculator_add_Results) String() string {
	str, _ := text.Marshal(0xe3188e9225bd9f50, capnp.Struct(s))
	return str
}

func (s Calculator_add_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Calculator_add_Results) DecodeFromPtr(p capnp.Ptr) Calculator_add_Results {
	return Calculator_add_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Calculator_add_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Calculator_add_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Calculator_add_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Calculator_add_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Calculator_add_Results) Sum() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s Calculator_add_Results) SetSum(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

// Calculator_add_Results_List is a list of Calculator_add_Results.
type Calculator_add_Results_List = capnp.StructList[Calculator_add_Results]

// NewCalculator_add_Results creates a new list of Calculator_add_Results.
func NewCalculator_add_Results_List(s *capnp.Segment, sz int32) (Calculator_add_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Calculator_add_Results](l), err
}

// Calculator_add_Results_Future is a wrapper for a Calculator_add_Results promised by a client call.
type Calculator_add_Results_Future struct{ *capnp.Future }

func (f Calculator_add_Results_Future) Struct() (Calculator_add_Results, error) {
	p, err := f.Future.Ptr()
	return Calculator_add_Results(p.Struct()), err
}

type Calculator_summarize_Params capnp.Struct

// Calculator_summarize_Params_TypeID is the unique identifier for the type Calculator_summarize_Params.
const Calculator_summarize_Params_TypeID = 0x945f8f4ab1e3560f

func NewCalculator_summarize_Params(s *capnp.Segment) (Calculator_summarize_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Calculator_summarize_Params(st), err
}

func NewRootCalculator_summarize_Params(s *capnp.Segment) (Calculator_summarize_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Calculator_summarize_Params(st), err
}

func ReadRootCalculator_summarize_Params(msg *capnp.Message) (Calculator_summarize_Params, error) {
	root, err := msg.Root()
	return Calculator_summarize_Params(root.Struct()), err
}

func (s Calculator_summarize_Params) String() string {
	str, _ := text.Marshal(0x945f8f4ab1e3560f, capnp.Struct(s))
	return str
}

func (s Calculator_summarize_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Calculator_summarize_Params) DecodeFromPtr(p capnp.Ptr) Calculator_summarize_Params {
	return Calculator_summarize_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Calculator_summarize_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Calculator_summarize_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Calculator_summarize_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Calculator_summarize_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Calculator_summarize_Params) Items() (ComplexItem_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ComplexItem_List(p.List()), err
}

func (s Calculator_summarize_Params) HasItems() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Calculator_summarize_Params) SetItems(v ComplexItem_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewItems sets the items field to a newly
// allocated ComplexItem_List, preferring placement in s's segment.
func (s Calculator_summarize_Params) NewItems(n int32) (ComplexItem_List, error) {
	l, err := NewComplexItem_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return ComplexItem_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Calculator_summarize_Params_List is a list of Calculator_summarize_Params.
type Calculator_summarize_Params_List = capnp.StructList[Calculator_summarize_Params]

// NewCalculator_summarize_Params creates a new list of Calculator_summarize_Params.
func NewCalculator_summarize_Params_List(s *capnp.Segment, sz int32) (Calculator_summarize_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Calculator_summarize_Params](l), err
}

// Calculator_summarize_Params_Future is a wrapper for a Calculator_summarize_Params promised by a client call.
type Calculator_summarize_Params_Future struct{ *capnp.Future }

func (f Calculator_summarize_Params_Future) Struct() (Calculator_summarize_Params, error) {
	p, err := f.Future.Ptr()
	return Calculator_summarize_Params(p.Struct()), err
}

type Calculator_summarize_Results capnp.Struct

// Calculator_summarize_Results_TypeID is the unique identifier for the type Calculator_summarize_Results.
const Calculator_summarize_Results_TypeID = 0xe33a51cd5127ae38

func NewCalculator_summarize_Results(s *capnp.Segment) (Calculator_summarize_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return Calculator_summarize_Results(st), err
}

func NewRootCalculator_summarize_Results(s *capnp.Segment) (Calculator_summarize_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return Calculator_summarize_Results(st), err
}

func ReadRootCalculator_summarize_Results(msg *capnp.Message) (Calculator_summarize_Results, error) {
	root, err := msg.Root()
	return Calculator_summarize_Results(root.Struct()), err
}

func (s Calculator_summarize_Results) String() string {
	str, _ := text.Marshal(0xe33a51cd5127ae38, capnp.Struct(s))
	return str
}

func (s Calculator_summarize_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Calculator_summarize_Results) DecodeFromPtr(p capnp.Ptr) Calculator_summarize_Results {
	return Calculator_summarize_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Calculator_summarize_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Calculator_summarize_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Calculator_summarize_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Calculator_summarize_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Calculator_summarize_Results) Count() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Calculator_summarize_Results) SetCount(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Calculator_summarize_Results) Checksum() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Calculator_summarize_Results) SetChecksum(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Calculator_summarize_Results) AmountSum() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s Calculator_summarize_Results) SetAmountSum(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s Calculator_summarize_Results) ScoreSum() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(24))
}

func (s Calculator_summarize_Results) SetScoreSum(v float64) {
	capnp.Struct(s).SetUint64(24, math.Float64bits(v))
}

// Calculator_summarize_Results_List is a list of Calculator_summarize_Results.
type Calculator_summarize_Results_List = capnp.StructList[Calculator_summarize_Results]

// NewCalculator_summarize_Results creates a new list of Calculator_summarize_Results.
func NewCalculator_summarize_Results_List(s *capnp.Segment, sz int32) (Calculator_summarize_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0}, sz)
	return capnp.StructList[Calculator_summarize_Results](l), err
}

// Calculator_summarize_Results_Future is a wrapper for a Calculator_summarize_Results promised by a client call.
type Calculator_summarize_Results_Future struct{ *capnp.Future }

func (f Calculator_summarize_Results_Future) Struct() (Calculator_summarize_Results, error) {
	p, err := f.Future.Ptr()
	return Calculator_summarize_Results(p.Struct()), err
}

type ComplexItem capnp.Struct

// ComplexItem_TypeID is the unique identifier for the type ComplexItem.
const ComplexItem_TypeID = 0xb9c12acaf55b835a

func NewComplexItem(s *capnp.Segment) (ComplexItem, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 1})
	return ComplexItem(st), err
}

func NewRootComplexItem(s *capnp.Segment) (ComplexItem, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 1})
	return ComplexItem(st), err
}

func ReadRootComplexItem(msg *capnp.Message) (ComplexItem, error) {
	root, err := msg.Root()
	return ComplexItem(root.Struct()), err
}

func (s ComplexItem) String() string {
	str, _ := text.Marshal(0xb9c12acaf55b835a, capnp.Struct(s))
	return str
}

func (s ComplexItem) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ComplexItem) DecodeFromPtr(p capnp.Ptr) ComplexItem {
	return ComplexItem(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ComplexItem) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ComplexItem) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ComplexItem) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ComplexItem) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ComplexItem) Id() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s ComplexItem) SetId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s ComplexItem) Category() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s ComplexItem) SetCategory(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s ComplexItem) Score() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(16))
}

func (s ComplexItem) SetScore(v float64) {
	capnp.Struct(s).SetUint64(16, math.Float64bits(v))
}

func (s ComplexItem) Amount() int64 {
	return int64(capnp.Struct(s).Uint64(24))
}

func (s ComplexItem) SetAmount(v int64) {
	capnp.Struct(s).SetUint64(24, uint64(v))
}

func (s ComplexItem) Flag() bool {
	return capnp.Struct(s).Bit(96)
}

func (s ComplexItem) SetFlag(v bool) {
	capnp.Struct(s).SetBit(96, v)
}

func (s ComplexItem) Label() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ComplexItem) HasLabel() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ComplexItem) LabelBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ComplexItem) SetLabel(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ComplexItem) AuxA() uint64 {
	return capnp.Struct(s).Uint64(32)
}

func (s ComplexItem) SetAuxA(v uint64) {
	capnp.Struct(s).SetUint64(32, v)
}

func (s ComplexItem) AuxB() uint64 {
	return capnp.Struct(s).Uint64(40)
}

func (s ComplexItem) SetAuxB(v uint64) {
	capnp.Struct(s).SetUint64(40, v)
}

func (s ComplexItem) Ratio() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(48))
}

func (s ComplexItem) SetRatio(v float64) {
	capnp.Struct(s).SetUint64(48, math.Float64bits(v))
}

// ComplexItem_List is a list of ComplexItem.
type ComplexItem_List = capnp.StructList[ComplexItem]

// NewComplexItem creates a new list of ComplexItem.
func NewComplexItem_List(s *capnp.Segment, sz int32) (ComplexItem_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 56, PointerCount: 1}, sz)
	return capnp.StructList[ComplexItem](l), err
}

// ComplexItem_Future is a wrapper for a ComplexItem promised by a client call.
type ComplexItem_Future struct{ *capnp.Future }

func (f ComplexItem_Future) Struct() (ComplexItem, error) {
	p, err := f.Future.Ptr()
	return ComplexItem(p.Struct()), err
}

const schema_c7d2d2b67fd7ab31 = "x\xda\x8cROh\x1ce\x1c}\xef\xfbf2\x1b\x9a" +
	"\xba\xf9\x9c9\x14mY([\xaa\x81\x96$*H\xa0" +
	"\xe4\x8f\x086 \xec\xb7\x0b\x82U\xd0/\xbb\xd34q" +
	"&\x1b\xe6\x0fM\xbdT\x11D/\x8a\xc5\x9eE\xf0&" +
	"\x08^\x0c\x1e*x\x90\x82\xa0`\xa1\x88\x17\x0f\xf6\xa0" +
	"(\x82B\x05\x0b\x95\x91ovgw\xad\x85\xf6\xb6\xf3" +
	"x\xfb\xde\xfb~\xef\xcd;b\xc5Y8x\xdc\x81\xd0" +
	"\xf3\xeeTqD\x9d?\xf3\xe6\x95\xe7\xdf\x82R\xb2X" +
	"\xf8\xf8\xfb\x8b\x9f]\xbbv\x15\xa0\x7f\x8b?\xf9\xae\xf0" +
	"\x00\x9f\xe2\xaa\xff\xba\xfdU\\\xffq\xff7~\xf4\xed" +
	"{P\x87\x09\xb8\xf4\x80\xc7\xb6\xc46A?\x17\xcb`" +
	"Q\x7f\xee\xc6\xa7\xeb\xef\xbe\xf4\xfe$\xe1\xf2\x80\xf0a" +
	"I\xd8~\xfb\xabtq\xfa\xe1}\xe8\xc3\x14\x80c\x09" +
	"\xdf\x89%K\xf8A\x9c\x07\x8b3o\xbc\xf0\xd7\xd7s" +
	"_~\x0e\xad\xe8\x8d\x03\x95R\xfe\x13\xf2W\x7fU\xda" +
	"\xff\x9c\x92\x05\xc1b\xff\xe9\xeb\xdb\x97\x16\xcf~1\xe9" +
	"\xb7\xeanX\xb9g]\xeb\xd7\xfa\xe0\xca\xb1K\xef\x1c" +
	"\xbaa\xfd8\xf4\x8b\xdd\xb52qIx\xf2\x93\xe3\xfa" +
	"\x1b\xbdT\x12\x9c!\xe1\xb2\x9b\x94\x89\xdd\x9fq\xa2\xe8" +
	"\x9a\xa8\x9bG&\x13\xfd\xe4d\xd7\xec\xee\xec.=5" +
	"@\xbc\xac\x9f\xb4H=#]`\x94\x84\xd5\x8d\x94^" +
	"\x87P\xa7=\x8e\x1f\xcd*\x8d:u\x14B-x\x14" +
	"\xa3\x8b\xb1\x0a\xa2\x8e\xb5!\xd4\x11\xafH\xcd\x85g\xc2" +
	"(\xea\x03X\xa1gz\xbd\x15\x16i\x1e\xc7&\xd9z" +
	"\x15\x0cW\xd8\"G\xe9\x9c;\xd3e\xfd\xe4d\xa5\xd0" +
	"l\x87i=\x8f\xb2T;\xd2\xbe\x91\x80:\xb8\x06\xe8" +
	"\x9a\xa4\x0e\x04/\xc6a\x9a\x9a\xcd\x903\x10\x9c\xc1\xbd" +
	"T\x87\x19\xc2f\xcb\xd4\x13\x13\xffGuq\xa8\xda\x14" +
	"llea\x9c\xf2\x01\xb0%\xc9\xd9q\xb3\xa0\x05G" +
	"&\xf2n&\xa6\xd7k.\xb7L)_\x1b\xc9?\xfa" +
	" \xa0\x9b\x92z^P\x91\x81\xadT\x9d\xb0\xe0#\x92" +
	"\xfaqA\x1a\xba\x10tAnT\xbf\xee\xd6`?\xde" +
	"\x8d\xc2\xbd\xfa\xe9,\x8cm\x85\xcd\x91\xc3\xef\x0f\x01\xfa" +
	"\x17I}\xd3:\x88\x81\xc3\x9f\xeb\x80\xfeCR\xdf\x16" +
	"TB\x04v\xb9\xea\x96}\xeaM\xc96\x05\x95\x94\x01" +
	"%\xa0\xfeY\x02\xf4\xdf\x92\x1d\xc7\xa2\xce\xcb\x81\xdd\x94" +
	"O\xce\x01\xfa\xb6d\xa7FA\xba\x01]\xc0w\xb9\x08" +
	"\xb4)\xd9\x99\xb1\xe4)'\xe0\x14\xe0O[r\xc7\xb1" +
	"\xf8\xac\xc5=7(\xb7\x7f\xb0\xc4k\x16\x0f,^\x9b" +
	"\x0aX\x03|ee:3\x16?DA\xb9\xd5\xe34" +
	"\x04\xa7\xcb\x87g\xe1f?\xb9\x00\x805\x08\xd6\xc0F" +
	"\xda\xed'!\x0f@\xf0\x00\xb8l\xe2~\xbe\x93U\x97" +
	"\xaa\x9f\x8d\xcc&\x09A\x82\x8d\xc8l\x84Q5\x89\xba" +
	"\xc9\xf7V+a\xfb\xb1V}4\x12\x93m\xf5+\xc5" +
	"\xfb\x1cd\xcb$\xde\x1d\xcb\x99\x1b\xef\xb1\xbec\xe2\xfb" +
	"\x1c\xa3\xddI;L\xed\xb81\xa9vt\xac\xe6\xa5y" +
	"\xfc\xbf-\xdcc\xd9\xed\xb0Qj\xea\xd9\x91\xa4\xb1}" +
	"\xbf(\xa9\xcfMl/\xb4\xcb\xe8I\xea\xdd\x89e\xc4" +
	"m@G\x92zob\x19\xb9ef\x92\xfa5\xc1F" +
	"\xb7\xbc\xfa\xa8\xa6sa\xf7\x954\x8fmM\x156(" +
	"\xa6\x93\x83\xe3\xeceu\x9d\x01ox\xee\x7f\x03\x00\x00" +
	"\xff\xffTaTH"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c7d2d2b67fd7ab31,
		Nodes: []uint64{
			0x8859bd865a77111d,
			0x91cea401ebb7ded5,
			0x945f8f4ab1e3560f,
			0xb71b093273c5896a,
			0xb9c12acaf55b835a,
			0xbe6632926ad545b7,
			0xe3188e9225bd9f50,
			0xe33a51cd5127ae38,
		},
		Compressed: true,
	})
}
