// Code generated by capnp. DO NOT EDIT.
// Regenerate with: capnp compile -I <capnp-std> -ogo calculator.capnp

package calc

import (
	context "context"
	math "math"

	capnp "capnproto.org/go/capnp/v3"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
)

type Calculator capnp.Client

// Calculator_TypeID is the unique identifier for the type Calculator.
const Calculator_TypeID = 0xf3d3ec35c0b0f001

func (c Calculator) SayHello(ctx context.Context, params func(Calculator_sayHello_Params) error) (Calculator_sayHello_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xf3d3ec35c0b0f001,
			MethodID:      0,
			InterfaceName: "calculator.capnp:Calculator",
			MethodName:    "sayHello",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(st capnp.Struct) error { return params(Calculator_sayHello_Params(st)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Calculator_sayHello_Results_Future{Future: ans.Future()}, release
}

func (c Calculator) Add(ctx context.Context, params func(Calculator_add_Params) error) (Calculator_add_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xf3d3ec35c0b0f001,
			MethodID:      1,
			InterfaceName: "calculator.capnp:Calculator",
			MethodName:    "add",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 0}
		s.PlaceArgs = func(st capnp.Struct) error { return params(Calculator_add_Params(st)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Calculator_add_Results_Future{Future: ans.Future()}, release
}

func (c Calculator) Summarize(ctx context.Context, params func(Calculator_summarize_Params) error) (Calculator_summarize_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xf3d3ec35c0b0f001,
			MethodID:      2,
			InterfaceName: "calculator.capnp:Calculator",
			MethodName:    "summarize",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(st capnp.Struct) error { return params(Calculator_summarize_Params(st)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Calculator_summarize_Results_Future{Future: ans.Future()}, release
}

func (c Calculator) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

func (c Calculator) String() string {
	return "Calculator(" + capnp.Client(c).String() + ")"
}

func (c Calculator) AddRef() Calculator {
	return Calculator(capnp.Client(c).AddRef())
}

func (c Calculator) Release() {
	capnp.Client(c).Release()
}

func (c Calculator) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Calculator) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Calculator) DecodeFromPtr(p capnp.Ptr) Calculator {
	return Calculator(capnp.Client{}.DecodeFromPtr(p))
}

func (c Calculator) IsValid() bool {
	return capnp.Client(c).IsValid()
}

func (c Calculator) IsSame(other Calculator) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

func (c Calculator) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

func (c Calculator) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Calculator_Server is a Calculator with a local implementation.
type Calculator_Server interface {
	SayHello(context.Context, Calculator_sayHello) error
	Add(context.Context, Calculator_add) error
	Summarize(context.Context, Calculator_summarize) error
}

// Calculator_NewServer creates a new Server from an implementation of Calculator_Server.
func Calculator_NewServer(s Calculator_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Calculator_Methods(nil, s), s, c)
}

// Calculator_ServerToClient creates a new Client from an implementation of Calculator_Server.
// The caller is responsible for calling Release on the returned Client.
func Calculator_ServerToClient(s Calculator_Server) Calculator {
	return Calculator(capnp.NewClient(Calculator_NewServer(s)))
}

// Calculator_Methods appends Methods to a slice that invoke the methods on s.
func Calculator_Methods(methods []server.Method, s Calculator_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf3d3ec35c0b0f001,
			MethodID:      0,
			InterfaceName: "calculator.capnp:Calculator",
			MethodName:    "sayHello",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.SayHello(ctx, Calculator_sayHello{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf3d3ec35c0b0f001,
			MethodID:      1,
			InterfaceName: "calculator.capnp:Calculator",
			MethodName:    "add",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Add(ctx, Calculator_add{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf3d3ec35c0b0f001,
			MethodID:      2,
			InterfaceName: "calculator.capnp:Calculator",
			MethodName:    "summarize",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Summarize(ctx, Calculator_summarize{call})
		},
	})

	return methods
}

// Calculator_sayHello holds the state for a server call to Calculator.sayHello.
type Calculator_sayHello struct {
	*server.Call
}

func (c Calculator_sayHello) Args() Calculator_sayHello_Params {
	return Calculator_sayHello_Params(c.Call.Args())
}

func (c Calculator_sayHello) AllocResults() (Calculator_sayHello_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Calculator_sayHello_Results(r), err
}

// Calculator_add holds the state for a server call to Calculator.add.
type Calculator_add struct {
	*server.Call
}

func (c Calculator_add) Args() Calculator_add_Params {
	return Calculator_add_Params(c.Call.Args())
}

func (c Calculator_add) AllocResults() (Calculator_add_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Calculator_add_Results(r), err
}

// Calculator_summarize holds the state for a server call to Calculator.summarize.
type Calculator_summarize struct {
	*server.Call
}

func (c Calculator_summarize) Args() Calculator_summarize_Params {
	return Calculator_summarize_Params(c.Call.Args())
}

func (c Calculator_summarize) AllocResults() (Calculator_summarize_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return Calculator_summarize_Results(r), err
}

type Calculator_sayHello_Params capnp.Struct

// Calculator_sayHello_Params_TypeID is the unique identifier for the type Calculator_sayHello_Params.
const Calculator_sayHello_Params_TypeID = 0xf3d3ec35c0b0f002

func NewCalculator_sayHello_Params(s *capnp.Segment) (Calculator_sayHello_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Calculator_sayHello_Params(st), err
}

func (s Calculator_sayHello_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Calculator_sayHello_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Calculator_sayHello_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Calculator_sayHello_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s Calculator_sayHello_Params) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Calculator_sayHello_Params) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Calculator_sayHello_Params) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

type Calculator_sayHello_Results capnp.Struct

// Calculator_sayHello_Results_TypeID is the unique identifier for the type Calculator_sayHello_Results.
const Calculator_sayHello_Results_TypeID = 0xf3d3ec35c0b0f003

func NewCalculator_sayHello_Results(s *capnp.Segment) (Calculator_sayHello_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Calculator_sayHello_Results(st), err
}

func (s Calculator_sayHello_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Calculator_sayHello_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Calculator_sayHello_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Calculator_sayHello_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s Calculator_sayHello_Results) MessageText() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Calculator_sayHello_Results) HasMessageText() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Calculator_sayHello_Results) SetMessageText(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Calculator_sayHello_Results_Future is a wrapper for a Calculator_sayHello_Results promised by a client call.
type Calculator_sayHello_Results_Future struct{ *capnp.Future }

func (f Calculator_sayHello_Results_Future) Struct() (Calculator_sayHello_Results, error) {
	p, err := f.Future.Ptr()
	return Calculator_sayHello_Results(p.Struct()), err
}

func (p Calculator_sayHello_Results_Future) MessageText() *capnp.Future {
	return p.Future.Field(0, nil)
}

type Calculator_add_Params capnp.Struct

// Calculator_add_Params_TypeID is the unique identifier for the type Calculator_add_Params.
const Calculator_add_Params_TypeID = 0xf3d3ec35c0b0f004

func NewCalculator_add_Params(s *capnp.Segment) (Calculator_add_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Calculator_add_Params(st), err
}

func (s Calculator_add_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Calculator_add_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Calculator_add_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Calculator_add_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s Calculator_add_Params) A() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s Calculator_add_Params) SetA(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s Calculator_add_Params) B() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s Calculator_add_Params) SetB(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

type Calculator_add_Results capnp.Struct

// Calculator_add_Results_TypeID is the unique identifier for the type Calculator_add_Results.
const Calculator_add_Results_TypeID = 0xf3d3ec35c0b0f005

func NewCalculator_add_Results(s *capnp.Segment) (Calculator_add_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Calculator_add_Results(st), err
}

func (s Calculator_add_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Calculator_add_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Calculator_add_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Calculator_add_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s Calculator_add_Results) Sum() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s Calculator_add_Results) SetSum(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

// Calculator_add_Results_Future is a wrapper for a Calculator_add_Results promised by a client call.
type Calculator_add_Results_Future struct{ *capnp.Future }

func (f Calculator_add_Results_Future) Struct() (Calculator_add_Results, error) {
	p, err := f.Future.Ptr()
	return Calculator_add_Results(p.Struct()), err
}

type ComplexItem capnp.Struct

// ComplexItem_TypeID is the unique identifier for the type ComplexItem.
const ComplexItem_TypeID = 0xf3d3ec35c0b0f006

func NewComplexItem(s *capnp.Segment) (ComplexItem, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 1})
	return ComplexItem(st), err
}

func (s ComplexItem) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s ComplexItem) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ComplexItem) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ComplexItem) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s ComplexItem) Id() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s ComplexItem) SetId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s ComplexItem) Category() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s ComplexItem) SetCategory(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s ComplexItem) Flag() bool {
	return capnp.Struct(s).Bit(96)
}

func (s ComplexItem) SetFlag(v bool) {
	capnp.Struct(s).SetBit(96, v)
}

func (s ComplexItem) Score() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(16))
}

func (s ComplexItem) SetScore(v float64) {
	capnp.Struct(s).SetUint64(16, math.Float64bits(v))
}

func (s ComplexItem) Amount() int64 {
	return int64(capnp.Struct(s).Uint64(24))
}

func (s ComplexItem) SetAmount(v int64) {
	capnp.Struct(s).SetUint64(24, uint64(v))
}

func (s ComplexItem) AuxA() uint64 {
	return capnp.Struct(s).Uint64(32)
}

func (s ComplexItem) SetAuxA(v uint64) {
	capnp.Struct(s).SetUint64(32, v)
}

func (s ComplexItem) AuxB() uint64 {
	return capnp.Struct(s).Uint64(40)
}

func (s ComplexItem) SetAuxB(v uint64) {
	capnp.Struct(s).SetUint64(40, v)
}

func (s ComplexItem) Ratio() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(48))
}

func (s ComplexItem) SetRatio(v float64) {
	capnp.Struct(s).SetUint64(48, math.Float64bits(v))
}

func (s ComplexItem) Label() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ComplexItem) HasLabel() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ComplexItem) SetLabel(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// ComplexItem_List is a list of ComplexItem.
type ComplexItem_List = capnp.StructList[ComplexItem]

func NewComplexItem_List(s *capnp.Segment, sz int32) (ComplexItem_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 56, PointerCount: 1}, sz)
	return capnp.StructList[ComplexItem](l), err
}

type Calculator_summarize_Params capnp.Struct

// Calculator_summarize_Params_TypeID is the unique identifier for the type Calculator_summarize_Params.
const Calculator_summarize_Params_TypeID = 0xf3d3ec35c0b0f007

func NewCalculator_summarize_Params(s *capnp.Segment) (Calculator_summarize_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Calculator_summarize_Params(st), err
}

func (s Calculator_summarize_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Calculator_summarize_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Calculator_summarize_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Calculator_summarize_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s Calculator_summarize_Params) Items() (ComplexItem_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ComplexItem_List(p.List()), err
}

func (s Calculator_summarize_Params) HasItems() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Calculator_summarize_Params) SetItems(v ComplexItem_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

func (s Calculator_summarize_Params) NewItems(n int32) (ComplexItem_List, error) {
	l, err := NewComplexItem_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return ComplexItem_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

type Calculator_summarize_Results capnp.Struct

// Calculator_summarize_Results_TypeID is the unique identifier for the type Calculator_summarize_Results.
const Calculator_summarize_Results_TypeID = 0xf3d3ec35c0b0f008

func NewCalculator_summarize_Results(s *capnp.Segment) (Calculator_summarize_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return Calculator_summarize_Results(st), err
}

func (s Calculator_summarize_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Calculator_summarize_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Calculator_summarize_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Calculator_summarize_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s Calculator_summarize_Results) Count() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Calculator_summarize_Results) SetCount(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Calculator_summarize_Results) Checksum() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Calculator_summarize_Results) SetChecksum(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Calculator_summarize_Results) AmountSum() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s Calculator_summarize_Results) SetAmountSum(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s Calculator_summarize_Results) ScoreSum() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(24))
}

func (s Calculator_summarize_Results) SetScoreSum(v float64) {
	capnp.Struct(s).SetUint64(24, math.Float64bits(v))
}

// Calculator_summarize_Results_Future is a wrapper for a Calculator_summarize_Results promised by a client call.
type Calculator_summarize_Results_Future struct{ *capnp.Future }

func (f Calculator_summarize_Results_Future) Struct() (Calculator_summarize_Results, error) {
	p, err := f.Future.Ptr()
	return Calculator_summarize_Results(p.Struct()), err
}
