package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"
)

// fileModel is the view passed to the code template.
type fileModel struct {
	Package    string
	Interfaces []ifaceModel
}

type ifaceModel struct {
	Name       string        // capnp interface name, e.g. "Calculator"
	Adapter    string        // "calculatorServerAdapter"
	ClientImpl string        // "calculatorClient"
	Methods    []methodModel // supported methods (typed Go API)
	All        []methodModel // every method (server adapter must cover all)
}

type methodModel struct {
	Name        string // PascalCase, e.g. "SayHello"
	Raw         string // schema name, e.g. "sayHello"
	Iface       string // owning interface name
	Unsupported string // non-empty when the method cannot be wrapped
	Params      []fieldModel
	Results     []fieldModel
}

func (m methodModel) ReqType() string  { return m.Name + "Request" }
func (m methodModel) RespType() string { return m.Name + "Response" }
func (m methodModel) CallType() string { return m.Iface + "_" + m.Raw }
func (m methodModel) ParamsType() string {
	return m.Iface + "_" + m.Raw + "_Params"
}

type fieldModel struct {
	Field  string // Go struct field, e.g. "Message"
	GoType string // e.g. "string"
	Getter string // capnp getter, e.g. "MessageText"
	Setter string // capnp setter, e.g. "SetMessageText"
	GetErr bool
	SetErr bool
}

// Generate turns .capnp source into a formatted *.capwrap.go file. Methods
// using types outside the MVP subset are reported in skipped so the CLI can
// warn about them.
func Generate(src string) (out []byte, skipped []string, err error) {
	s, err := parse(src)
	if err != nil {
		return nil, nil, err
	}

	model := fileModel{Package: s.Package}
	for _, in := range s.Interfaces {
		im := ifaceModel{
			Name:       in.Name,
			Adapter:    lowerFirst(in.Name) + "ServerAdapter",
			ClientImpl: lowerFirst(in.Name) + "Client",
		}
		for _, m := range in.Methods {
			mm := methodModel{
				Name:        pascal(m.Name),
				Raw:         m.Name,
				Iface:       in.Name,
				Unsupported: m.Unsupported,
				Params:      fieldModels(m.Params),
				Results:     fieldModels(m.Results),
			}
			im.All = append(im.All, mm)
			if m.Unsupported == "" {
				im.Methods = append(im.Methods, mm)
			} else {
				skipped = append(skipped, fmt.Sprintf("%s.%s: %s", in.Name, m.Name, m.Unsupported))
			}
		}
		model.Interfaces = append(model.Interfaces, im)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, model); err != nil {
		return nil, nil, err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, nil, fmt.Errorf("format generated code: %w\n%s", err, buf.String())
	}
	return formatted, skipped, nil
}

func fieldModels(fields []field) []fieldModel {
	out := make([]fieldModel, 0, len(fields))
	for _, f := range fields {
		info, _ := f.Type.info()
		acc := accessor(f)
		out = append(out, fieldModel{
			Field:  pascal(f.Name),
			GoType: info.GoType,
			Getter: acc,
			Setter: "Set" + acc,
			GetErr: info.GetterErr,
			SetErr: info.SetterErr,
		})
	}
	return out
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

var tmpl = template.Must(template.New("capwrap").Parse(`// Code generated by capwrap-gen. DO NOT EDIT.

package {{.Package}}

import (
	"context"

	capnp "capnproto.org/go/capnp/v3"
	capwrap "github.com/Huy-8bit/capwrap/runtime"
)

{{range .Interfaces}}
// {{.Name}}Server is the service interface application code implements.
type {{.Name}}Server interface {
{{- range .Methods}}
	{{.Name}}(context.Context, *{{.ReqType}}) (*{{.RespType}}, error)
{{- end}}
}

// {{.Name}}Client calls a remote {{.Name}} service.
type {{.Name}}Client interface {
{{- range .Methods}}
	{{.Name}}(context.Context, *{{.ReqType}}) (*{{.RespType}}, error)
{{- end}}
	Close() error
}

{{range .Methods}}
type {{.ReqType}} struct {
{{- range .Params}}
	{{.Field}} {{.GoType}}
{{- end}}
}

type {{.RespType}} struct {
{{- range .Results}}
	{{.Field}} {{.GoType}}
{{- end}}
}
{{end}}

// Register{{.Name}}Server installs impl as the server's bootstrap capability.
func Register{{.Name}}Server(s *capwrap.Server, impl {{.Name}}Server) {
	s.SetBootstrap(capnp.Client({{.Name}}_ServerToClient({{.Adapter}}{impl})))
}

type {{.Adapter}} struct {
	impl {{.Name}}Server
}

{{$adapter := .Adapter}}
{{range .All}}
func (s {{$adapter}}) {{.Name}}(ctx context.Context, call {{.CallType}}) error {
{{- if .Unsupported}}
	// {{.Unsupported}}
	return capwrap.Errorf("method {{.Name}} is not supported by the capwrap wrapper")
{{- else}}
	args := call.Args()
{{- range .Params}}
	arg{{.Field}}{{if .GetErr}}, err{{end}} := args.{{.Getter}}()
{{- if .GetErr}}
	if err != nil {
		return err
	}
{{- end}}
{{- end}}
	resp, err := s.impl.{{.Name}}(ctx, &{{.ReqType}}{
{{- range .Params}}
		{{.Field}}: arg{{.Field}},
{{- end}}
	})
	if err != nil {
		return err
	}
	results, err := call.AllocResults()
	if err != nil {
		return err
	}
{{- range .Results}}
{{- if .SetErr}}
	if err := results.{{.Setter}}(resp.{{.Field}}); err != nil {
		return err
	}
{{- else}}
	results.{{.Setter}}(resp.{{.Field}})
{{- end}}
{{- end}}
	return nil
{{- end}}
}
{{end}}

// Dial{{.Name}} connects to a {{.Name}} service at addr.
func Dial{{.Name}}(ctx context.Context, addr string, opts ...capwrap.DialOption) ({{.Name}}Client, error) {
	cc, err := capwrap.Dial(ctx, addr, opts...)
	if err != nil {
		return nil, err
	}
	return &{{.ClientImpl}}{cc: cc, raw: {{.Name}}(cc.Bootstrap(ctx))}, nil
}

type {{.ClientImpl}} struct {
	cc  *capwrap.ClientConn
	raw {{.Name}}
}

func (c *{{.ClientImpl}}) Close() error {
	c.raw.Release()
	return c.cc.Close()
}

{{$impl := .ClientImpl}}
{{range .Methods}}
func (c *{{$impl}}) {{.Name}}(ctx context.Context, req *{{.ReqType}}) (*{{.RespType}}, error) {
	future, release := c.raw.{{.Name}}(ctx, func(p {{.ParamsType}}) error {
{{- range .Params}}
{{- if .SetErr}}
		if err := p.{{.Setter}}(req.{{.Field}}); err != nil {
			return err
		}
{{- else}}
		p.{{.Setter}}(req.{{.Field}})
{{- end}}
{{- end}}
		return nil
	})
	defer release()

	res, err := future.Struct()
	if err != nil {
		return nil, capwrap.WrapError(err)
	}
{{- range .Results}}
	ret{{.Field}}{{if .GetErr}}, err{{end}} := res.{{.Getter}}()
{{- if .GetErr}}
	if err != nil {
		return nil, capwrap.WrapError(err)
	}
{{- end}}
{{- end}}
	return &{{.RespType}}{
{{- range .Results}}
		{{.Field}}: ret{{.Field}},
{{- end}}
	}, nil
}
{{end}}
{{end}}`))
